// Helper to create empty cpomStructures for tests
export const createEmptyCpomStructures = () => ({
  cpomStructures: [],
});

export const createValidBudget = (overrides = {}) => ({
  id: 1,
  year: 2024,
  ETP: 1.5,
  tauxEncadrement: 0.8,
  coutJournalier: 50,
  dotationDemandee: 100000,
  dotationAccordee: 95000,
  totalProduitsProposes: 95000,
  totalProduits: 95000,
  totalChargesProposees: 90000,
  totalCharges: 90000,
  repriseEtat: 0,
  excedentRecupere: 0,
  excedentDeduit: 0,
  affectationReservesFondsDedies: 0,
  fondsDedies: 0,
  reserveInvestissement: null,
  chargesNonReconductibles: null,
  reserveCompensationDeficits: null,
  reserveCompensationBFR: null,
  reserveCompensationAmortissements: null,
  reportANouveau: null,
  autre: null,
  commentaire: null,
  ...overrides,
});

// Helper for autoriseeCurrentYear budget
export const createBudgetAutoriseeCurrentYear = (overrides = {}) => ({
  id: 1,
  year: 2024,
  ETP: 1.5,
  tauxEncadrement: 0.8,
  coutJournalier: 50,
  dotationDemandee: 100000,
  dotationAccordee: 95000,
  totalProduits: null,
  totalCharges: null,
  repriseEtat: null,
  excedentRecupere: null,
  excedentDeduit: null,
  affectationReservesFondsDedies: null,
  cumulResultatsNetsCPOM: null,
  totalChargesProposees: null,
  reserveInvestissement: null,
  chargesNonReconductibles: null,
  reserveCompensationDeficits: null,
  reserveCompensationBFR: null,
  reserveCompensationAmortissements: null,
  fondsDedies: null,
  commentaire: null,
  ...overrides,
});

// Helper for autoriseeY2 budget
export const createBudgetAutoriseeY2 = (overrides = {}) => ({
  id: 2,
  year: 2025,
  ETP: 1.5,
  tauxEncadrement: 0.8,
  coutJournalier: 50,
  dotationDemandee: 100000,
  dotationAccordee: 95000,
  totalProduits: null,
  totalCharges: null,
  repriseEtat: null,
  excedentRecupere: null,
  excedentDeduit: null,
  affectationReservesFondsDedies: null,
  cumulResultatsNetsCPOM: null,
  totalChargesProposees: null,
  reserveInvestissement: null,
  chargesNonReconductibles: null,
  reserveCompensationDeficits: null,
  reserveCompensationBFR: null,
  reserveCompensationAmortissements: null,
  fondsDedies: null,
  commentaire: null,
  ...overrides,
});

// Helper for sansCpom budget (matches budgetAutoriseeOpenSchema)
export const createBudgetSansCpom = (overrides = {}) => ({
  id: 4,
  year: 2024,
  ETP: 1.5,
  tauxEncadrement: 0.8,
  coutJournalier: 50,
  dotationDemandee: 100000,
  dotationAccordee: 95000,
  totalProduitsProposes: 95000,
  totalProduits: 95000,
  totalChargesProposees: 90000,
  totalCharges: 90000,
  repriseEtat: 0,
  excedentRecupere: 0,
  excedentDeduit: 0,
  affectationReservesFondsDedies: 0,
  fondsDedies: 0,
  reserveInvestissement: null,
  chargesNonReconductibles: null,
  reserveCompensationDeficits: null,
  reserveCompensationBFR: null,
  reserveCompensationAmortissements: null,
  reportANouveau: null,
  autre: null,
  commentaire: null,
  ...overrides,
});

// Helper for avecCpom budget (matches budgetAutoriseeOpenSchema)
export const createBudgetAvecCpom = (overrides = {}) => ({
  id: 5,
  year: 2024,
  ETP: 1.5,
  tauxEncadrement: 0.8,
  coutJournalier: 50,
  dotationDemandee: 100000,
  dotationAccordee: 95000,
  totalProduitsProposes: 95000,
  totalProduits: 95000,
  totalChargesProposees: 90000,
  totalCharges: 90000,
  repriseEtat: 0,
  excedentRecupere: 0,
  excedentDeduit: 0,
  affectationReservesFondsDedies: 0,
  fondsDedies: 0,
  reserveInvestissement: null,
  chargesNonReconductibles: null,
  reserveCompensationDeficits: null,
  reserveCompensationBFR: null,
  reserveCompensationAmortissements: null,
  reportANouveau: null,
  autre: null,
  commentaire: null,
  ...overrides,
});
