-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'AGENT_NATIONAL', 'AGENT_REGIONAL', 'AGENT_DEPARTEMENTAL', 'ANONYMOUS');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "UserRole" NOT NULL DEFAULT 'ANONYMOUS';
