export const EVALUATION_ADVANCE_MONTHS = 18;
export const CONVENTION_ADVANCE_MONTHS = 3;
export const AUTORISATION_ADVANCE_MONTHS = 3;

export const EVALUATION_PERIOD_YEARS = 5;
export const EVALUATION_PERIODS_COUNT = 3;
