-- AlterEnum
ALTER TYPE "TransformationType" ADD VALUE 'TRANSFO_HUDA_FERMETURE_VERS_CADA_EXISTANT';
ALTER TYPE "TransformationType" ADD VALUE 'TRANSFO_HUDA_FERMETURE_VERS_CADA_NOUVEAU';
ALTER TYPE "TransformationType" ADD VALUE 'TRANSFO_HUDA_FERMETURE_REMISE_EN_CONCURRENCE';
ALTER TYPE "TransformationType" ADD VALUE 'TRANSFO_HUDA_CONTRACTION_VERS_CADA_EXISTANT';
ALTER TYPE "TransformationType" ADD VALUE 'TRANSFO_HUDA_CONTRACTION_VERS_CADA_NOUVEAU';
ALTER TYPE "TransformationType" ADD VALUE 'TRANSFO_HUDA_CONTRACTION_REMISE_EN_CONCURRENCE';
