export const AnomalieCode = [
  "AUTORISATION_DUREE_NOT_15Y",
  "CONVENTION_AUTORISEE_DUREE_NOT_5Y",
  "CONVENTION_SUBVENTIONNEE_DUREE_GT_3Y",
  "CONVENTION_HORS_PERIODE_AUTORISATION",
  "CONVENTION_MANQUANTE_OU_EXPIREE",
  "CONVENTION_DATES_DIFFERENTES_ACTES",
  "AUTORISATION_DATES_DIFFERENTES_ACTES",
  "EVALUATION_HORS_DELAI",
  "PLACES_LABELLISEES_GT_AUTORISEES",
  "PLACES_SPECIALISEES_GT_AUTORISEES",
  "PLACES_PMR_GT_AUTORISEES",
  "INCOHERENCE_LGBT_PLACES",
  "INCOHERENCE_FVVTEH_PLACES",
  "PLACES_ADRESSES_ECART_STRUCTURE",
  "DEPARTEMENT_INCOHERENT_CODE_DNA",
  "MULTI_DNA",
  "CPOM_MONO_STRUCTURE",
  "TAUX_ENCADREMENT_GT_SEUIL",
  "TAUX_ENCADREMENT_LT_2",
  "COUT_JOURNALIER_GT_TARIF_CIBLE",
  "COUT_JOURNALIER_LT_15",
  "RESULTAT_NET_EQ_0",
  "AFFECTATION_DETAIL_MANQUANT",
  "AFFECTATION_DETAIL_ECART",
  "REPRISE_PLUS_AFFECTATION_ECART",
  "REPRISE_ETAT_SIGNE_INVERSE",
  "SUBVENTIONNEE_DEFICIT_AVEC_EXCEDENT",
  "SUBVENTIONNEE_EXCEDENT_AVEC_REPRISE_ETAT",
  "SUBVENTIONNEE_EXCEDENT_ECART",
  "DOCUMENT_CONVENTION_MANQUANT",
  "DOCUMENT_AUTORISATION_MANQUANT",
  "DOCUMENT_CPOM_MANQUANT",
  "ACTIVITE_PLACES_INDISPONIBLES_GT_3PCT",
  "ACTIVITE_PRESENCES_INDUES_GT_7PCT",
] as const;

export type AnomalieCode = (typeof AnomalieCode)[number];

export const AnomalieCategory = [
  "CALENDAR",
  "PLACES",
  "CHARACTERISTICS",
  "FINANCE",
  "DOCUMENTS",
  "ACTIVITE",
] as const;

export type AnomalieCategory = (typeof AnomalieCategory)[number];

// Table pointée par targetId. STRUCTURE => targetId reste à 0.
export const AnomalieTarget = [
  "STRUCTURE",
  "ACTE_ADMINISTRATIF",
  "ADRESSE",
  "CPOM",
  "DNA",
] as const;

export type AnomalieTarget = (typeof AnomalieTarget)[number];

export const ANOMALIE_NO_YEAR = 0;
export const ANOMALIE_TARGET_STRUCTURE = 0;
