CREATE TYPE "UserActionType" AS ENUM (
  'STATISTIQUES_TABLE',
  'STATISTIQUES_CARTOGRAPHIE',
  'STRUCTURES_CARTOGRAPHIE',
  'TYPE_PLACES_SPREADSHEET_EXPORT',
  'FINANCES_SPREADSHEET_EXPORT',
  'CONTROLE_QUALITE_SPREADSHEET_EXPORT',
  'STRUCTURE_SPREADSHEET_EXPORT',
  'STRUCTURE_PDF_EXPORT',
  'STATISTIQUES_SPREADSHEET_EXPORT',
  'STATISTIQUES_PDF_EXPORT'
);

ALTER TABLE "UserAction" RENAME COLUMN "description" TO "type";

ALTER TABLE "UserAction" ALTER COLUMN "type" TYPE "UserActionType" USING "type"::text::"UserActionType";

DROP TYPE "UserActionDescription";

ALTER TABLE "UserAction" ADD COLUMN "details" TEXT;